general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[mouse]
hide_when_typing = true

[cursor.style]
shape = "Beam"
blinking = "Always"

[window]
opacity = 0.7
decorations = "None"
blur = true

[terminal]
shell = "/usr/bin/fish"

[font.normal]
family = "NotoSansM Nerd Font"
style = "Regular"

[font.bold]
family = "NotoSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "NotoSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "NotoSansM Nerd Font"
style = "Italic"
